[package]
name = "libafl-sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libafl = "0.11.1"
libafl_bolts = "0.11.1"
